CREATE SCHEMA `test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE `test`.`tasks` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  `STATE` BIT(1) NOT NULL,
  PRIMARY KEY (`ID`));
