CREATE SCHEMA `test`
  DEFAULT CHARACTER SET utf8
  COLLATE utf8_general_ci;

CREATE TABLE `test`.`tasks` (
  `ID`          INT          NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  `STATE`       BOOLEAN      NOT NULL DEFAULT 0,
  `CREATED`     TIMESTAMP,
  `PRIORITY`    INT          NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
);
